aa: rand-m9-mstd0.5-inc1
accum_iter: 1 # actual batch = accum_iter * batch_size * num_gpus
batch_size: 64
epochs: 200
cutmix: 1.0
data_dir: ''
dataset: imagenet
input_size: 224
min_lr: 0.25e-5
mixup: 0.25
mixup_prob: 0.5
model: maxformer_10_384
blr: 0.00135
seed: 42
time_step: 4
warmup:epochs: 5
