aa: rand-m9-mstd0.5-inc1
batch_size: 64
embed_dims: 512
epochs: 200
cutmix: 1.0
data_dir: ''
dataset: imagenet
input_size: 224
min_lr: 1e-5
mixup: 0.2
mixup_prob: 0.5
blr: 0.0012
seed: 42
time_step: 1
warmup:epochs: 5
